#!/bin/bash

function get_subdomain_info() {
  domain=$1
  subdomain=$2

  dig +short "$subdomain.$domain" | awk '/ANSWER SECTION:/ { getline; print $0 }'
}

if [[ $# -eq 1 ]]; then
  for subdomain in www lb-01 web-01 web-02; do
    info=$(get_subdomain_info "$1" "$subdomain")
    echo "The subdomain $subdomain is a ${info%% *} record and points to ${info##* }"
  done
else
  info=$(get_subdomain_info "$1" "$2")
  echo "The subdomain $2 is a ${info%% *} record and points to ${info##* }"
fi
