#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver web-01 54.167.146.86:80 check\n\tserver web-02 54.157.189.37:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
