#!/usr/bin/env bash
# congigures an nginx

# remove the default nginx confi file
rm /etc/nginx/sites-enabled/default
# configure nginx to listen on port 80
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
sudo service nginx restart
