#!/usr/bin/env bash
# This script displays a list of currently running processes.

# Use the ps command with options to format the output
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
