#!/usr/bin/env bash
#This script displays "Best School" 10 times but displays "hi" on the 9th

i=0

while [[ $i -lt 10 ]]
do
	echo "Best School"
	if [[ $i -eq 8 ]]
	then
		echo "Hi"
	fi
	let "i += 1"
done
