#!/usr/bin/env bash
# This script displays "Best School" 10 times with "Hi" on the 9th iteration.

# Initialize a counter
count=0

# Use a while loop to repeat the message 10 times
while [ $count -lt 10 ]
do
    if [ $count -eq 8 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi

    ((count++))
done
