#!/usr/bin/env bash
# This script displays "Best School" 9 times and "Hi" on the 9th iteration

hour=0

while (( hour <= 12 ))
do
        echo "Hour: $hour"
        minute=1
        while (( minute <= 59 ))
        do
                echo "$minute"
                (( minute++ ))
        done
        (( hour++ ))
done